name: Python unittest

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  python_unittest:
    name: Python unittest

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install PyArrow
      run: pip3 install pyarrow
    - name: Python unittest
      run: python3 -m unittest --verbose
